# VALEX PROXY SSL

server {
    listen 443 ssl;
    server_name {{VALEX_DOMAIN}};

    ssl_certificate     {{VALEX_SSL_CERT}};
    ssl_certificate_key {{VALEX_SSL_KEY}};

    location / {
        proxy_pass {{VALEX_PROXY_PASS}};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name {{VALEX_DOMAIN}};
    return 301 https://$host$request_uri;
}
